### ISSUE TITLE
UI tesztek írása

### ISSUE THREAD

**Issue by Katinka666** [BME-MIT-IET/iet-hf-2023-csapat1000#17]
A projekt felhasználói felületének automatizált tesztelése szükséges, hogy a felhasználó szempontjából vizsgálhassuk az elkészült program működését. Ebben az issue-ban azt nézzük meg, hogy a tényleges felhasználói felületen az alkalmazás funkcionalitása az elvárásoknak megfelelően működik-e, a lehető legjobban utánozva a valós világban lezajló folyamatokat.

**Comment by lucakovacs** [comment]
A UI tesztek helyett a manuális tesztelés feladatot válaszotttuk.
