### ISSUE TITLE
SpotBugs tesztek

### ISSUE THREAD

**Issue by kololilla** [BME-MIT-IET/iet-hf-2023-csapat1000#18]
A SpotBugs programmal készített tesztelése a programnak, bugok keresése a kódban.

**Comment by kololilla** [comment]
Feladatok:
- [x] Függvény nevek kezdőbetűje kis betűvel kezdődjön. *(Method names should start with a lower case letter)*
- [x] Controller.Game.run függvény switch statement-nek default ágat készíteni. *(Switch statement found where default case is missing)*
- [x] Adapter mezők final-lá változtatása a következő osztályokban: L.Agent, L.Code, L.Field, L.Gear, L.Material, L.Player *(Field isn't final but should be)*
- [x] Final w és h mezők statikussá tétele a view.Window osztályban. *(Unread field: should this field be static?)*

**Comment by kololilla** [comment]
Talált hiba [Class defines clone() but doesn't implement Cloneable] a Bear osztályban. Ez javításra szorul?

**Comment by lucakovacs** [comment]
Szerintem nem szükséges, mert ahogy néztem csak naming szempontból clone nem viselkedésben,

**Comment by lucakovacs** [comment]
@kololilla ebben az issue-ban lesz még változtatásod?

**Comment by kololilla** [comment]
A kódszerkezetet nem nagyon befolyásoló hibákat javítottam, a többit idő hiányában toleráltam. Lezárom az issuet.

**Comment by kololilla** [comment]
A kódszerkezetet nem nagyon befolyásoló hibákat javítottam, a többit idő hiányában toleráltam. Lezárom az issuet.

**Comment by lucakovacs** [comment]
PR még nincs
