### ISSUE TITLE
Code coverage teszt beüzemelése

### ISSUE THREAD

**Issue by jud11t** [BME-MIT-IET/iet-hf-2023-csapat1000#20]
Szeretnénk ellenőrizni a projektünk kódlefedettségét, így ebben az issue-ban ennek megvalósításával fogunk foglalkozni.

**Comment by jud11t** [comment]
A JaCoCo nem tud report-ot generálni tesztek nélkül, így ezt az issue-t nem tudom lezárni addig, amíg a #5 alatt lévő commit-ok be nem lettek mergelve. 

A saját gépemen a másik branch-en, ahol a teszteket írom leteszteltem és nálam működött.

**Comment by lucakovacs** [comment]
Szerintem ettől függetlenül lehetne rá nyitni egy pull request-et, mert ha jól tudom fordítási hibát nem okoz.
