### ISSUE TITLE
Unit tesztek írása

### ISSUE THREAD

**Issue by jud11t** [BME-MIT-IET/iet-hf-2023-csapat1000#5]
Projekt laboratórium során Unit tesztelésre nem volt szükség, így a projekten belül egységtesztek készítése (esetleges kiegészítése), elsődlegesen Unit tesztekkel.
@jud11t

**Comment by lucakovacs** [comment]
@jud11t a JUnit dependenciát így tudod hozzáadni a projekthez: https://mvnrepository.com/artifact/junit/junit/4.13.1

**Comment by jud11t** [comment]
A unit tesztek írásával elég lassan tudok haladni, ezt holnap tudom befejezni csak :( 
Elég sok olyan osztályt vagy függvényt találtam, ami nagyon nehezen leválasztható és unit tesztelhető, de igyekszem a lehető legtöbbet dologra tesztet írni.
